begin
  require 'jeweler'
  Jeweler::Tasks.new do |gemspec|
    gemspec.name = "gosu_extensions"
    gemspec.summary = "Default extensions built onto the popular Gosu Framework. Uses Chipmunk for game physics. That's it for now. I'm working on them. Anyway, GAME ON!"
    gemspec.email = "florian.hanke@gmail.com"
    gemspec.homepage = "http://www.github.com/floere/gosu_extensions"
    gemspec.description = ""
    gemspec.authors = ["Florian Hanke", "Severin Schoepke (various improvements)"]
    gemspec.rdoc_options = ["--inline-source", "--charset=UTF-8"]
    gemspec.files = FileList["[A-Z]*", "{generator,lib}/**/*"]
    gemspec.test_files = FileList["spec/**/*_spec.rb"]
    gemspec.add_dependency 'gosu'
    gemspec.add_dependency 'chipmunk'
    # gemspec.bindir = 'bin'
    # gemspec.executables = ['bin/gogogosu']
    # gemspec.default_executable = 'bin/gogogosu'
  end
  Jeweler::GemcutterTasks.new
rescue LoadError => e
  puts "Jeweler not available (#{e}). Install it with: sudo gem install technicalpickles-jeweler -s http://gems.github.com"
end

require 'spec'
require 'spec/rake/spectask'
desc "Run all specs in spec directory"
Spec::Rake::SpecTask.new(:spec) do |t|
  t.spec_files = FileList['spec/**/*_spec.rb']
end

task :default => :spec